version: '3.8'

services:
  db:
    build: ./database
    image: debilla/spidertracks-test-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    networks:
      - backend
      - frontend

  app-ws:
    depends_on:
      - db
    build: ./app-ws
    image: debilla/spidertracks-test-ws
    ports:
      - 8080:8080
    networks:
      - backend
      - frontend

  app-ui:
    depends_on:
      - app-ws
    build: ./app-ui
    image: debilla/spidertracks-test-ui
    ports:
      - 80:80
    networks:
      - frontend


networks:
  backend:
  frontend:
